<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{36ee831a-606f-4333-b640-1a57f50c75a5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fValue : LREAL;
	nValue : UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>